twitter-to-kafka-service:
  twitter-keywords:
    - sports
  welcome-message: Hello World
enable-v2-tweets: true
enable-mock-tweets: false
twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream
twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
twitter-v2-bearer-token: AAAAAAAAAAAAAAAAAAAAADac0AEAAAAAXjKOFeopcEPY5CO65yy31YQMK84%3DI6zjoUhPoZrgs6wyKULxzNrRXDgj6kvgK2kdNECfUedQV46kZh